### ISSUE TITLE
Chatty json decoding issue

### ISSUE THREAD

**Issue by Day0Dreamer** [WatchBeam/beam-client-python#9]
There I was, running the example.py and nothing worked :D

***
PS C:\Users\DayDreamer-i7\Desktop\beam-client-python-master> C:\Python34\python.exe .\example.py`

Traceback (most recent call last):
  File ".\example.py", line 20, in <module>
    chat.authenticate()
  File "C:\Users\DayDreamer-i7\Desktop\beam-client-python-master\chatty\connection.py", line 54, in authenticate
    self._get_chat_details()
  File "C:\Users\DayDreamer-i7\Desktop\beam-client-python-master\chatty\connection.py", line 33, in _get_chat_details
    self.userid = requests.get(url=url, headers=header).json()['id']

KeyError: 'id'
***

**Comment by Purzifal** [comment]
Did you remember to config.example.py to config.py  and ammend with your authentication information. seems like its not authenticating you. did you also create an oauth client on your account, https://mixer.com/lab , its the only thing I can think of that could be causing this, I don't have my development laptop with me so I cannot really confirm.

@Day0Dreamer I will check this when I get home in about 1.5 hours

EDIT: @connor4312 or @SimonSchick  you can close this issue as this was due to wrong user settings in config.py

**Comment by Rhinorulz** [comment]
Hey, i'm just gonna sneek in here, and say that i have this same issue, and do have my token/secret and id in config.py
